{% set name = "ghcup" %}
{% set version = "0.1.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.haskell.org/~ghcup/{{ version }}/aarch64-apple-darwin-ghcup-{{ version }}  # [osx and arm64]
  sha256: 69bd8e37cd07606d928dca9215c066564a264e0def3c81171b76d5747dc6507c  # [osx and arm64]
  url: https://downloads.haskell.org/~ghcup/{{ version }}/aarch64-linux-ghcup-{{ version }}  # [linux and aarch64]
  sha256: a546dcd23a7e56f31bc4d6afad0276f88d3f0b850a3d3c36369721797dc3c3d5  # [linux and aarch64]
  url: https://downloads.haskell.org/~ghcup/{{ version }}/x86_64-apple-darwin-ghcup-{{ version }}  # [osx and x86_64]
  sha256: 416de8509092fd95f97ee19a5f3def91fbd6e6fa4fa630a5c5e7226f49a83af7  # [osx and x86_64]
  url: https://downloads.haskell.org/~ghcup/{{ version }}/x86_64-linux-ghcup-{{ version }}  # [linux and x86_64]
  sha256: 33ee6a758ee06e3b520be176905e6192e31f5fa2e2acdc525b1bea77ca368a12  # [linux and x86_64]
  url: https://downloads.haskell.org/~ghcup/{{ version }}/x86_64-mingw64-ghcup-{{ version }}.exe  # [win]
  sha256: c80008f5d7b19770fbfbe7759136c0f6313de0cfd6d2c9b5e60438ce29d23f29  # [win]
  fn: ghcup  # [not win]
  fn: ghcup.exe  # [win]

build:
  number: 0
  binary_relocation: false

requirements:
  run:
    - curl

test:
  commands:
    - ghcup -h
    - if [ "$GHCUP_INSTALL_BASE_PREFIX" != "$PREFIX" ]; then echo "GHCUP_INSTALL_BASE_PREFIX var not set correctly" && exit 1; fi    # [unix]
    - if [ "$GHCUP_SKIP_UPDATE_CHECK" != "1" ]; then echo "GHCUP_SKIP_UPDATE_CHECK var not set correctly" && exit 1; fi    # [unix]
    - IF "%GHCUP_INSTALL_BASE_PREFIX:/=\%" NEQ "%LIBRARY_PREFIX%" exit 1    # [win]
    - IF "%GHCUP_SKIP_UPDATE_CHECK%" NEQ "1" exit 1    # [win]

about:
  home: https://gitlab.haskell.org/haskell/ghcup-hs
  summary: An installer for the general purpose language Haskell
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSE.txt
    - dependency_licenses.txt

extra:
  recipe-maintainers:
    - msarahan
