{% set name = "ghcup" %}
{% set version = "0.1.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.haskell.org/~ghcup/{{ version }}/aarch64-apple-darwin-ghcup-{{ version }}  # [osx and arm64]
  sha256: 30450031c47226f4bdd75de6e7bacb3e9abe1808ecf8e9a42e00cf3d10fd0dee  # [osx and arm64]
  url: https://downloads.haskell.org/~ghcup/{{ version }}/aarch64-linux-ghcup-{{ version }}  # [linux and aarch64]
  sha256: f6931479132040039a23cff244c04defe51b701a29590b35b739a5505f43d678  # [linux and aarch64]
  url: https://downloads.haskell.org/~ghcup/{{ version }}/x86_64-apple-darwin-ghcup-{{ version }}  # [osx and x86_64]
  sha256: a19f73dcffe921418b4da6cd49efc6e43a2fd804030be2928437ed21cb1e902c  # [osx and x86_64]
  url: https://downloads.haskell.org/~ghcup/{{ version }}/x86_64-linux-ghcup-{{ version }}  # [linux and x86_64]
  sha256: d1e7e7edaf8fb336c783fe0aac937e25178e6d9043ecbc9984d14b37f963a305  # [linux and x86_64]
  url: https://downloads.haskell.org/~ghcup/{{ version }}/x86_64-mingw64-ghcup-{{ version }}.exe  # [win]
  sha256: 3140d37b69ce111a144d4d9ce4408f59e7372eb37d68d80a76718d2812a2e21a  # [win]
  fn: ghcup  # [not win]
  fn: ghcup.exe  # [win]

build:
  number: 0
  binary_relocation: false

requirements:
  run:
    - curl

test:
  commands:
    - ghcup -h
    - if [ "$GHCUP_INSTALL_BASE_PREFIX" != "$PREFIX" ]; then echo "GHCUP_INSTALL_BASE_PREFIX var not set correctly" && exit 1; fi    # [unix]
    - if [ "$GHCUP_SKIP_UPDATE_CHECK" != "1" ]; then echo "GHCUP_SKIP_UPDATE_CHECK var not set correctly" && exit 1; fi    # [unix]
    - IF "%GHCUP_INSTALL_BASE_PREFIX:/=\%" NEQ "%LIBRARY_PREFIX%" exit 1    # [win]
    - IF "%GHCUP_SKIP_UPDATE_CHECK%" NEQ "1" exit 1    # [win]

about:
  home: https://gitlab.haskell.org/haskell/ghcup-hs
  summary: An installer for the general purpose language Haskell
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSE.txt
    - dependency_licenses.txt

extra:
  recipe-maintainers:
    - msarahan
