{% set name = "ghcup" %}
{% set version = "0.1.19.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.haskell.org/~ghcup/{{ version }}/aarch64-apple-darwin-ghcup-{{ version }}  # [osx and arm64]
  sha256: ea1f70a049d15f7d296f9ca1fe788ac4d9120c7962edce9aacbbaf06f70095d6  # [osx and arm64]
  url: https://downloads.haskell.org/~ghcup/{{ version }}/aarch64-linux-ghcup-{{ version }}  # [linux and aarch64]
  sha256: 7ab3606f3de49c363444dd5879edde27a3e7df0adbd981a8c12a153861fde271  # [linux and aarch64]
  url: https://downloads.haskell.org/~ghcup/{{ version }}/x86_64-apple-darwin-ghcup-{{ version }}  # [osx and x86_64]
  sha256: b0ee8f9604810b51253754dca326bc03592e2b866bf1177755de102f26e729d8  # [osx and x86_64]
  url: https://downloads.haskell.org/~ghcup/{{ version }}/x86_64-linux-ghcup-{{ version }}  # [linux and x86_64]
  sha256: 25b7fc417c1a811dd7ff439b67ea647a59cf5b8d71b274f97e917d50b2150d5b  # [linux and x86_64]
  url: https://downloads.haskell.org/~ghcup/{{ version }}/x86_64-mingw64-ghcup-{{ version }}.exe  # [win]
  sha256: 8cac0e2cbd1ffe8609fc457ac491dea3b98d9332966a46b8f643a6d42ffc22b1  # [win]
  fn: ghcup  # [not win]
  fn: ghcup.exe  # [win]

build:
  number: 0
  binary_relocation: false

requirements:
  run:
    - curl

test:
  commands:
    - ghcup -h
    - if [ "$GHCUP_INSTALL_BASE_PREFIX" != "$PREFIX" ]; then echo "GHCUP_INSTALL_BASE_PREFIX var not set correctly" && exit 1; fi    # [unix]
    - if [ "$GHCUP_SKIP_UPDATE_CHECK" != "1" ]; then echo "GHCUP_SKIP_UPDATE_CHECK var not set correctly" && exit 1; fi    # [unix]
    - IF "%GHCUP_INSTALL_BASE_PREFIX:/=\%" NEQ "%LIBRARY_PREFIX%" exit 1    # [win]
    - IF "%GHCUP_SKIP_UPDATE_CHECK%" NEQ "1" exit 1    # [win]

about:
  home: https://gitlab.haskell.org/haskell/ghcup-hs
  summary: An installer for the general purpose language Haskell
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSE.txt
    - dependency_licenses.txt

extra:
  recipe-maintainers:
    - msarahan
